"""
seed_data.py - 대시보드 데모용 샘플 데이터 생성

실제 아프리카 시장 모니터 가격 수준을 반영한 현실적인 데이터입니다.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent))

from database.db_manager import DatabaseManager

PRODUCTS = [
    # ── Kenya (KES) ───────────────────────────────────────────────
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"HP V214a 20.7 Inch HD Monitor","brand":"HP","model":"V214A","screen_size_inch":20.7,"resolution":"1366x768","refresh_rate":60,"panel_type":"TN","condition":"new","price":8999,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/hp-v214a-monitor-1.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"HP 22es 21.5 Inch FHD IPS Monitor","brand":"HP","model":"22ES","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":13500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/hp-22es-monitor-2.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"HP 24f 23.8 Inch FHD Monitor","brand":"HP","model":"24F","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":17500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/hp-24f-monitor-3.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Samsung 22 Inch LED Monitor LS22F350","brand":"Samsung","model":"LS22F350","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":11800,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/samsung-22-monitor-4.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Samsung 24 Inch FHD Monitor S24F354","brand":"Samsung","model":"S24F354","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":16800,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/samsung-24-monitor-5.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"LG 22MK600M 22 Inch IPS Monitor","brand":"LG","model":"22MK600M","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":12500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/lg-22mk600-monitor-6.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"LG 24MK430H 24 Inch FHD Monitor","brand":"LG","model":"24MK430H","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":15900,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/lg-24mk430-monitor-7.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Dell E2216H 22 Inch LED Monitor","brand":"Dell","model":"E2216H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":14200,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/dell-e2216h-monitor-8.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Dell P2419H 24 Inch IPS Monitor","brand":"Dell","model":"P2419H","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":22500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/dell-p2419h-monitor-9.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"AOC 22B2H 22 Inch FHD Frameless Monitor","brand":"AOC","model":"22B2H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":10500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/aoc-22b2h-monitor-10.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"AOC 24B2XH 24 Inch IPS Monitor","brand":"AOC","model":"24B2XH","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":14800,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/aoc-24b2xh-monitor-11.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Acer KA220HQ 21.5 Inch FHD Monitor","brand":"Acer","model":"KA220HQ","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":9800,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/acer-ka220hq-monitor-12.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Acer R240HY 23.8 Inch IPS Monitor","brand":"Acer","model":"R240HY","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":14500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/acer-r240hy-monitor-13.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"ViewSonic VA2215-H 22 Inch FHD Monitor","brand":"ViewSonic","model":"VA2215-H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"VA","condition":"new","price":11200,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/viewsonic-va2215-monitor-14.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Lenovo L24i-30 23.8 Inch FHD Monitor","brand":"Lenovo","model":"L24I-30","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":75,"panel_type":"VA","condition":"new","price":16500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/lenovo-l24i-monitor-15.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Dell S2721D 27 Inch QHD IPS Monitor","brand":"Dell","model":"S2721D","screen_size_inch":27.0,"resolution":"2560x1440","refresh_rate":75,"panel_type":"IPS","condition":"new","price":35000,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/dell-s2721d-monitor-16.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"HP E27 G4 27 Inch FHD IPS Monitor","brand":"HP","model":"E27G4","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":29500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/hp-e27g4-monitor-17.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Samsung 27 Inch Curved FHD Monitor C27F396","brand":"Samsung","model":"C27F396","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":26000,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/samsung-c27f396-monitor-18.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"HP 22 Inch Monitor - Refurbished","brand":"HP","model":None,"screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"refurbished","price":7500,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/hp-22-refurb-monitor-19.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Kenya","retailer":"Jumia Kenya","product_title":"Dell 24 Inch Monitor Used Good Condition","brand":"Dell","model":None,"screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"used","price":9000,"currency":"KES","availability":"in stock","product_url":"https://www.jumia.co.ke/dell-24-used-monitor-20.html","image_url":None,"crawl_date":"2026-05-19"},

    # ── Ghana (GHS) ───────────────────────────────────────────────
    {"country":"Ghana","retailer":"CompuGhana","product_title":"HP V214a 20.7 Inch HD Monitor","brand":"HP","model":"V214A","screen_size_inch":20.7,"resolution":"1366x768","refresh_rate":60,"panel_type":"TN","condition":"new","price":790,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/hp-v214a-monitor-1.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"HP 22es 21.5 Inch FHD IPS Monitor","brand":"HP","model":"22ES","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":1180,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/hp-22es-monitor-2.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"HP 24f 23.8 Inch FHD Monitor","brand":"HP","model":"24F","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":1580,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/hp-24f-monitor-3.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Samsung 22 Inch LED Monitor LS22F350","brand":"Samsung","model":"LS22F350","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":980,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/samsung-22-monitor-4.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Samsung 24 Inch FHD Monitor S24F354","brand":"Samsung","model":"S24F354","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":1380,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/samsung-24-monitor-5.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"LG 22MK600M 22 Inch IPS 75Hz Monitor","brand":"LG","model":"22MK600M","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":1050,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/lg-22mk600-monitor-6.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Dell E2220H 21.5 Inch FHD Monitor","brand":"Dell","model":"E2220H","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":1250,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/dell-e2220h-monitor-7.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"AOC 22B2H 22 Inch FHD Monitor","brand":"AOC","model":"22B2H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":920,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/aoc-22b2h-monitor-8.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Acer KA222Q 21.5 Inch FHD Monitor","brand":"Acer","model":"KA222Q","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":890,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/acer-ka222q-monitor-9.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"ViewSonic VA2215-H 22 Inch Monitor","brand":"ViewSonic","model":"VA2215-H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"VA","condition":"new","price":960,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/viewsonic-va2215-monitor-10.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Philips 243V7QJABF 23.8 Inch IPS Monitor","brand":"Philips","model":"243V7QJABF","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":1320,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/philips-243v7-monitor-11.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"BenQ GW2280 22 Inch FHD Monitor","brand":"BenQ","model":"GW2280","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":1100,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/benq-gw2280-monitor-12.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"LG 27MK600M 27 Inch IPS Monitor","brand":"LG","model":"27MK600M","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":2100,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/lg-27mk600-monitor-13.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"HP 27f 27 Inch FHD IPS Monitor","brand":"HP","model":"27F","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":2350,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/hp-27f-monitor-14.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Samsung 32 Inch Curved Monitor C32F391","brand":"Samsung","model":"C32F391","screen_size_inch":32.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":3200,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/samsung-c32f391-monitor-15.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"HP 22 Inch Monitor Refurbished","brand":"HP","model":None,"screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"refurbished","price":620,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/hp-22-refurb-monitor-16.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Dell 24 Inch Used Monitor","brand":"Dell","model":None,"screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"used","price":780,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/dell-24-used-monitor-17.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Acer 27 Inch QHD Gaming Monitor XB271HU","brand":"Acer","model":"XB271HU","screen_size_inch":27.0,"resolution":"2560x1440","refresh_rate":144,"panel_type":"IPS","condition":"new","price":4500,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/acer-xb271hu-monitor-18.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"MSI Optix G24 24 Inch 144Hz Gaming Monitor","brand":"MSI","model":"OPTIX G24","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":144,"panel_type":"TN","condition":"new","price":2800,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/msi-optix-g24-monitor-19.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Ghana","retailer":"CompuGhana","product_title":"Lenovo ThinkVision T24i 23.8 Inch IPS Monitor","brand":"Lenovo","model":"T24I","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":1480,"currency":"GHS","availability":"in stock","product_url":"https://www.compughana.com/lenovo-t24i-monitor-20.html","image_url":None,"crawl_date":"2026-05-19"},

    # ── Nigeria (NGN) ─────────────────────────────────────────────
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"HP V214a 20.7 Inch HD Monitor","brand":"HP","model":"V214A","screen_size_inch":20.7,"resolution":"1366x768","refresh_rate":60,"panel_type":"TN","condition":"new","price":49000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/hp-v214a-monitor-1.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"HP 22es 21.5 Inch FHD IPS Monitor","brand":"HP","model":"22ES","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":72000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/hp-22es-monitor-2.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"HP 24f 23.8 Inch FHD Monitor","brand":"HP","model":"24F","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":95000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/hp-24f-monitor-3.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Samsung 22 Inch LED Monitor LS22F350","brand":"Samsung","model":"LS22F350","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":65000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/samsung-22-monitor-4.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Samsung 24 Inch FHD Curved Monitor","brand":"Samsung","model":"S24F354","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":85000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/samsung-24-monitor-5.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"LG 22MK600M 22 Inch IPS 75Hz Monitor","brand":"LG","model":"22MK600M","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":68000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/lg-22mk600-monitor-6.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"LG 24MK430H 24 Inch FHD IPS Monitor","brand":"LG","model":"24MK430H","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":88000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/lg-24mk430-monitor-7.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Dell E2216H 22 Inch FHD Monitor","brand":"Dell","model":"E2216H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"TN","condition":"new","price":79000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/dell-e2216h-monitor-8.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Dell P2419H 24 Inch IPS Monitor","brand":"Dell","model":"P2419H","screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"new","price":125000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/dell-p2419h-monitor-9.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"AOC 22B2H 22 Inch FHD Frameless Monitor","brand":"AOC","model":"22B2H","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":58000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/aoc-22b2h-monitor-10.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"AOC 27B2H 27 Inch FHD Monitor","brand":"AOC","model":"27B2H","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":98000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/aoc-27b2h-monitor-11.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Acer KA222Q 21.5 Inch FHD Monitor","brand":"Acer","model":"KA222Q","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":52000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/acer-ka222q-monitor-12.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"ViewSonic VA2715-H 27 Inch FHD Monitor","brand":"ViewSonic","model":"VA2715-H","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":75,"panel_type":"VA","condition":"new","price":105000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/viewsonic-va2715-monitor-13.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Lenovo L24i-30 23.8 Inch FHD Monitor","brand":"Lenovo","model":"L24I-30","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":75,"panel_type":"VA","condition":"new","price":89000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/lenovo-l24i-monitor-14.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Philips 243V7QJABF 23.8 Inch IPS Monitor","brand":"Philips","model":"243V7QJABF","screen_size_inch":23.8,"resolution":"1920x1080","refresh_rate":75,"panel_type":"IPS","condition":"new","price":78000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/philips-243v7-monitor-15.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"BenQ GW2280 22 Inch Eye-Care Monitor","brand":"BenQ","model":"GW2280","screen_size_inch":22.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":62000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/benq-gw2280-monitor-16.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Asus VP228H 21.5 Inch FHD Gaming Monitor","brand":"Asus","model":"VP228H","screen_size_inch":21.5,"resolution":"1920x1080","refresh_rate":75,"panel_type":"TN","condition":"new","price":61000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/asus-vp228h-monitor-17.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"Samsung 27 Inch Curved Monitor C27F396","brand":"Samsung","model":"C27F396","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"VA","condition":"new","price":145000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/samsung-c27f396-monitor-18.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"MSI Optix G27 27 Inch 144Hz Gaming Monitor","brand":"MSI","model":"OPTIX G27","screen_size_inch":27.0,"resolution":"1920x1080","refresh_rate":144,"panel_type":"IPS","condition":"new","price":185000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/msi-optix-g27-monitor-19.html","image_url":None,"crawl_date":"2026-05-19"},
    {"country":"Nigeria","retailer":"Jumia Nigeria","product_title":"HP 24 Inch Monitor Used Second Hand","brand":"HP","model":None,"screen_size_inch":24.0,"resolution":"1920x1080","refresh_rate":60,"panel_type":"IPS","condition":"used","price":38000,"currency":"NGN","availability":"in stock","product_url":"https://www.jumia.com.ng/hp-24-used-monitor-20.html","image_url":None,"crawl_date":"2026-05-19"},
]

if __name__ == "__main__":
    db = DatabaseManager()
    new_c, upd_c = db.bulk_upsert(PRODUCTS)
    print(f"완료: {new_c}개 신규 저장, {upd_c}개 업데이트")
    print(f"DB 총 상품 수: {db.total_products()}")
    stats = db.get_summary_stats()
    print("\n국가별 통계:")
    for row in stats["by_country"]:
        print(f"  {row['country']}: {row['total']}개, 평균가 {row['avg_price']:,.0f} {row['currency']}")
